### ISSUE TITLE
Recover the AES encryption key with the AES spy

### ISSUE THREAD

**Issue by glemartin** [cispa/Security-RISC#1]
Hello,

I am trying to implement the flush and reload attack on the AES on a CVA6 core. I have done the compilation for both openSSL and your AES program on the CVA6, and I am able to get the numbers of hit access on the probe.
I'm now trying to recover the encryption key from these results.
Do you have any script to perform the statistical analysis on the results produced by this program and recover the key?

Thank you in advance
Gwendal Le Martin

**Comment by s8lvg** [comment]
Hi, 
we do not provide end-to-end AES key recovery attacks. 
However, as soon as you have good measurements, the key can be recovered, for example, by the approach presented in [Efficient Cache Attacks on AES, and Countermeasures](https://cs-people.bu.edu/tromer/papers/cache-joc-official.pdf)
